export const changeWeahterData = (data) => {
    return {
        type: "CHANGE_WEATHER_DATA",

        location: data.location,
        day: data.day,

        currentTemp: data.currentTemp,
        currentFeels_like: data.currentFeels_like,
        currentDescription: data.currentDescription,
        currentIcon: data.currentIcon,
        currentMax: data.currentMax,
        currentMin: data.currentMin,
        currentPrecipProbability: data.currentPrecipProbability,
        currentWindSpeed: data.currentWindSpeed,

        day2Max: data.day2Max,
        day2Min: data.day2Min,
        day2FeelsLikeMax: data.day2FeelsLikeMax,
        day2FeelsLikeMin: data.day2FeelsLikeMin,
        day2Description: data.day2Description,
        day2PrecipProbability: data.day2PrecipProbability,
        day2Icon: data.day2Icon,
        day2Day: data.day2Day,

        day3Max: data.day3Max,
        day3Min: data.day3Min,
        day3FeelsLikeMax: data.day3FeelsLikeMax,
        day3FeelsLikeMin: data.day3FeelsLikeMin,
        day3Description: data.day3Description,
        day3PrecipProbability: data.day3PrecipProbability,
        day3Icon: data.day3Icon,
        day3Day: data.day3Day,

        day4Max: data.day4Max,
        day4Min: data.day4Min,
        day4FeelsLikeMax: data.day4FeelsLikeMax,
        day4FeelsLikeMin: data.day4FeelsLikeMin,
        day4Description: data.day4Description,
        day4PrecipProbability: data.day4PrecipProbability,
        day4Icon: data.day4Icon,
        day4Day: data.day4Day,

        day5Max: data.day4Max,
        day5Min: data.day5Min,
        day5FeelsLikeMax: data.day5FeelsLikeMax,
        day5FeelsLikeMin: data.day5FeelsLikeMin,
        day5Description: data.day5Description,
        day5PrecipProbability: data.day5PrecipProbability,
        day5Icon: data.day5Icon,
        day5Day: data.day5Day,

        day6Max: data.day6Max,
        day6Min: data.day6Min,
        day6FeelsLikeMax: data.day6FeelsLikeMax,
        day6FeelsLikeMin: data.day6FeelsLikeMin,
        day6Description: data.day6Description,
        day6PrecipProbability: data.day6PrecipProbability,
        day6Icon: data.day6Icon,
        day6Day: data.day6Day,

        day7Max: data.day7Max,
        day7Min: data.day7Min,
        day7FeelsLikeMax: data.day7FeelsLikeMax,
        day7FeelsLikeMin: data.day7FeelsLikeMin,
        day7Description: data.day7Description,
        day7PrecipProbability: data.day7PrecipProbability,
        day7Icon: data.day7Icon,
        day7Day: data.day7Day,
    }
}